### ISSUE TITLE
Settings don't seem to save on my Gosund SP111 (using the Blitzwolf bwshpx.bin)

### ISSUE THREAD

**Issue by MarcoV1980** [mcspr/espurna-nightly-builder#10]
Hi there,

i flashed espurna-1.15.0-dev.gita2c02a38+nightly20211020-blitzwolf-bwshpx.bin to my Gosund Sp111 which was already using 14.1 fine, but i wanted to see what new was in store with an eventual upgrade.

I flashed the core-webui file first, then flashed the normal file through the webui. All seems to install fine, but there are some weird things i've noticed.

For one, the Power units and the Energy units settings don't seem to work. It shows the energy unit standard in J, but when i set it to W it just says nothing has changed, and i can't seem to this working.

Also have an idea that the http api doesn't work properly, i'm using these plugs with Homey and on 14.1 they were working fine, but with this i cannot seem to connect to my Homey anymore. Even removed and tried readding, even tried different HTTP  API keys but unfortunately it didn't work. Last i did a factory reset on the power plug itself, reset everything but above issues kept popping up.

Am i missing a step somewhere, or are there still some issues?

Thanks for all your work!

**Comment by mcspr** [comment]
> For one, the Power units and the Energy units settings don't seem to work. It shows the energy unit standard in J, but when i set it to W it just says nothing has changed, and i can't seem to this working.

Just a display issue. You can check via debug panel `get eneUnits0` - 15 is J, 16 is kwh;
`set eneUnits0 16` and `reload`, after page reload will show correct units on the home page.

> Also have an idea that the http api doesn't work properly, i'm using these plugs with Homey and on 14.1 they were working fine, but with this i cannot seem to connect to my Homey anymore. Even removed and tried readding, even tried different HTTP API keys but unfortunately it didn't work. Last i did a factory reset on the power plug itself, reset everything but above issues kept popping up.

I'd appreciate a concrete example, can't fix just by guessing what is wrong :) Flashing .bin you mentioned on a test device with api key 'testtest'
```
curl -H'Api-Key: testtest' http://10.10.10.54/api/metrics
relay0 0
current 0.000
voltage 0
power 0
reactive 0
apparent 0
factor 0
energy_delta 0
energy 0.000
```

And pls notice that this is not an issue tracker for the ESPurna, but the nightly-builder app
