### ISSUE TITLE
Encendido automatico no programado

### ISSUE THREAD

**Issue by adolfossl** [mcspr/espurna-nightly-builder#4]
Hola!!!
He detectado que cuando se activa un schedule cualquiera, además el evento programado también se ejecuta un encendido a la 01:30 y otro sobre las 04:00. Esto no ocurre si no hay ningún schedule activo.
Lo he comprobado con dos Sonoff, el S26 y el basic.

Gracias

**Comment by mcspr** [comment]
Did you mean to send issue to the https://github.com/xoseperez/espurna?
If your problem is with espurna firmware running on sonoff devices you mentioned, refer there

**Comment by adolfossl** [comment]
Ok, thank you.
