### ISSUE TITLE
nightly builds stopped?

### ISSUE THREAD

**Issue by victorclaessen** [mcspr/espurna-nightly-builder#5]
Hi, it seems there haven't been any nightly builds for a while. Is something broken?

**Comment by mcspr** [comment]
I temporarily disabled them some time ago and forgot to reschedule travis cron.
On again. But, building is *slooooow* during european day. And turns out current `dev` cannot build fully:
https://travis-ci.org/mcspr/espurna-nightly-builder/jobs/512070679#L984

**Comment by victorclaessen** [comment]
Thanks for the quick response. Will check in a few days to see if the build succeeds again.
