### ISSUE TITLE
sonoff-basic nightly build

### ISSUE THREAD

**Issue by scargill** [mcspr/espurna-nightly-builder#6]
I''ve used sonoff-th nightly build here over the last 2 days - works perfectly and relay status (th16/relay/0) correctly reports the status of the relay - 1 or 0 for on or off

But sonoff-basic nightly on a sonoff basic board (WIFI) always operates the relay perfectly but the status (sandy/relay/0) always returns 1 using alexa or the button or mqtt.

Strangely if I put the TH nightly build into the Sonof basic WIFI board, everything works perfectly including the status.

**Comment by mcspr** [comment]
Thank you for noticing this!
The difference between versions is in date btw, note a different "Firmware revision" and "Firmware build date" on the status page. MQTT payload should be fixed rn.

But, please use this tracker for problems with nightly builder itself. If you have any issues with the current version of ESPurna, just post an issue at the https://github.com/xoseperez/espurna/issues instead.

**Comment by scargill** [comment]
And indeed it IS fixed. I just downloaded the latest nightly build. Sorry for commenting in the wrong place, I'm still new to ESPurna.

**Comment by mcspr** [comment]
Nah, no worry. It could be a logistical error on my part, these could be released in the @xoseperez repo instead of here, to avoid mixing up tool issues and firmware issues.
