### ISSUE TITLE
NOTICE about the builder

### ISSUE THREAD

**Issue by mcspr** [mcspr/espurna-nightly-builder#8]
https://docs.travis-ci.com/user/billing-overview/#free-plan-credits
> Each new user gets automatically assigned to the Free Plan upon signing up. The Free plan contains a one time pool of Credits, not renewable. This plan is meant to let you familiarize with our usage based plans as well as to try out other Travis CI features.

At Jan 21 credits expired, meaning https://travis-ci.com/github/mcsp account is totally useless now.

Since I <s>am a cheapskate</s> don't want to use Travis CI anymore, will need to adapt some other service. Gitlab still feels too convoluted, and Github already has a serviceable replacement already available. Pending https://github.com/letscontrolit/ESPEasy/issues/3462 to figure out a correct approach to releases

**Comment by WhoCares1337** [comment]
Travis just added 25000 credits. Espurna qualifies for their free for open source program. They wrote "When your credits begin running low again, please reach back out to the Support team."

**Comment by mcspr** [comment]
Thanks! I missed the gitter message... Looking at the travis account dashboard, there are indeed 24440 credits now
(although, it is interesting that those are not OSS-specific ones, but just plain generic credits)

Cron had triggered the build, but now there seems to be a problem with OS image being outdated

**Comment by WhoCares1337** [comment]
Issue closed xD
