### ISSUE TITLE
Cant upgrade sonoff RFbridge

### ISSUE THREAD

**Issue by nortuzar** [mcspr/espurna-nightly-builder#9]
Hi, I'm trying to upgrade from the stable release to the last nightly, I follow the instruction using the web GUI, so I first upgrade using the file
`espurna-1.15.0-dev.git509bbea7+nightly20211004-espurna-core-webui-1MB.bin`
but after that, when I try to flash the `espurna-1.15.0-dev.git509bbea7+nightly20211004-itead-sonoff-rfbridge.bin` 
I still receive the message `Image it too large to fit in the available space for OTA. Consider doing a two-step update`

Is not possible to use this method with the sonoff rf bridge?

Thanks for your help

**Comment by mcspr** [comment]
Have you tried [compression with gzip?](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#compression)

WebUI binary can also be built with `-DESPURNA_CORE_WEBUI -DWEB_SUPPORT=0 -DOTA_WEB_SUPPORT=1` to shrink it to 395664 bytes which... should fit the rfbridge.bin?

**Comment by nortuzar** [comment]
> 
> 
> Have you tried [compression with gzip?](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#compression)
> 
> WebUI binary can also be built with `-DESPURNA_CORE_WEBUI -DWEB_SUPPORT=0 -DOTA_WEB_SUPPORT=1` to shrink it to 395664 bytes which... should fit the rfbridge.bin?

Thanks, using 7zip to compress the bin `espurna-1.15.0-dev.git509bbea7+nightly20211004-itead-sonoff-rfbridge.bin` with format gzip work!

Again thanks for the quick reply
